### ISSUE TITLE
header fonts not showing properly

### ISSUE THREAD

**Issue by cscrum** [angular-ui/ui-grid#1786]
Here is a simple example of a grid that I am trying to enable filtering on. I'm getting strange fonts and the filter cells are not showing. Any idea of what I could be doing wrong?

**Comment by anyong** [comment]
I read the couple of threads on here, and the tutorial section on fonts - still having issues. the GET requests to my fonts appear to work normally coming back with 200 OK, but I'm still seeing Korean on my ui-grids. (That's Korean, by the way, it's not Chinese or "Chinese-like", hah.)

**Comment by PaulL1** [comment]
Hmm.  Usually it is something misconfigured in your build scripts or some form of caching issue.  But if it's loading the fonts properly, then that's a bit surprising.  You don't have some part of your application expecting them in one location (and therefore loading them) and another part of your application expecting them somewhere else?  I'm assuming the fonts are still working fine for you on the tutorials?

**Comment by henry74** [comment]
Getting this same issue with the Korean characters showing in the header.

**Comment by naijenn** [comment]
I feel its important to note that font-awesome and bootstrap both target their fonts in a fonts directory and at this time ui-grid does not. I believe many do apply these fonts into a 'fonts directory' to eliminate clutter, and as ui-grid targets the main 'dist' directory, my fonts were technically installed in the wrong location. 

As I have no intention of changing my fonts location, an easy fix was simply to override the @font-face class (in this case to the fonts directory)...
```css
@font-face {
  font-family: 'ui-grid';
  src: url('../fonts/ui-grid.eot');
  src: url('../fonts/ui-grid.eot#iefix') format('embedded-opentype'), url('../fonts/ui-grid.woff') format('woff'), url('../fonts/ui-grid.ttf?') format('truetype'), url('../fonts/ui-grid.svg?#ui-grid') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
