### ISSUE TITLE
Add wordwrap and tooltip

### ISSUE THREAD

**Issue by pisaacs** [angular-ui/ui-grid#317]
Great job on ng-grid - a serious contender to replacing the fame Adobe Flex DataGrid. 

I think two features would be great additions: cell word wrapping and tooltip. Word wrapping would automatically adjust the height of the row. For tooltip, this would especially be useful for abridged cell content, which shows ellipses. 

An example of how these could be used:
{ field:'description', displayName:'Description', minWidth:200, wordWrap:true, toolTip:'description'},

**Comment by ericj79** [comment]
I realize this is already closed, but since this is the most informative post I could find when I was trying to get text to wrap, I thought I would share my solution here. I use CSS instead of a new row template. 
Just include the following in a CSS file. *I  include my file after the ui-grid CSS file, but I don't know if that is necessary*:

**NOTE:** *This relies on browsers supporting Flex-Box. If you have to support older browsers, this may not work for you.*

```css
.ui-grid-viewport .ui-grid-cell-contents {
  word-wrap: break-word;
  white-space: normal !important;
}

.ui-grid-row, .ui-grid-cell {
  height: auto !important;
}

.ui-grid-row div[role=row] {
  display: flex ;
  align-content: stretch;
}
```
