### ISSUE TITLE
Undesired column menu animation change

### ISSUE THREAD

**Issue by wattsbn** [angular-ui/ui-grid#3436]
When switching from 3.0.0-rc.20 to 3.0.0-rc.21, I noticed a change in the column menu animation. It used to be nice and subtle, but it now comes down from the top of the page.
Hopefully this is just a bug and not an intentional change.

You can see it on the main demo page (using Chrome if that matters).
http://ui-grid.info/

**Comment by PaulL1** [comment]
Yeah, it's a bug.  I think it was an attempt to fix column menu positioning on IE9 that broke it, although I haven't bisected yet to prove that.  @c0bra

**Comment by PaulL1** [comment]
Hmm.  Or maybe it's not that at all.  I seem to recall doing a change where I moved where in the directives the menu lived.  Perhaps that did it.

**Comment by PaulL1** [comment]
Hmm.  I bisected all the way back into Dec.  It seems to have always done it.  Interesting.

**Comment by ronaldcs** [comment]
Ran into this weird issue too...but the animation seems to *not* be present in http://ui-grid.info/customizer/?

**Comment by ronaldcs** [comment]
I think I found it. It's related to the UI Grid CSS (in the case of ui-grid-unstable.css, line 146):

```css
.ui-grid-column-menu .ui-grid-menu .ui-grid-menu-mid.ng-hide-add,
.ui-grid-column-menu .ui-grid-menu .ui-grid-menu-mid.ng-hide-remove {
  -webkit-transition: all 0.05s linear;
  -moz-transition: all 0.05s linear;
  -o-transition: all 0.05s linear;
  transition: all 0.05s linear;
  display: block !important;
}
```

Comment out the above lines in the CSS and the animation goes away.
