### ISSUE TITLE
improve styling for ui-grid-filter in IE

### ISSUE THREAD

**Issue by SoundLogic** [angular-ui/ui-grid#4649]
IE10+ adds an `x` to allow users to clear inputs when inputs go over a certain size
Adding this simple CSS would resolve this issue:

``` css
  .ui-grid-filter-container input::-ms-clear {
      display: none;
      width : 0;
      height: 0;
  }
```
