### ISSUE TITLE
csslint error in ui-grid.css: ms-keyframes

### ISSUE THREAD

**Issue by FloMaetschke** [angular-ui/ui-grid#4716]
It seems there is a problem with [csslint](https://github.com/CSSLint/csslint) and [ui-grid.css (compiled from animation.less)](https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/less/animation.less#L56-L70).

``` css
@-ms-keyframes ui-grid-spin {
  0% {
    -moz-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -moz-transform: rotate(359deg);
    -o-transform: rotate(359deg);
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}
```

This results in an error when running csslint.
"Unknown @ rule: @-ms-keyframes."

I suggest removing it should fix it.
