### ISSUE TITLE
Spanning Column Headers

### ISSUE THREAD

**Issue by megbers** [angular-ui/ui-grid#644]
Was wondering if there was a simple way to get multiple-column spanning for headers?  It would be ideal if there was a way to group columns under a spanning header.  If not, is this a feature that you could see implementing?

**Comment by rajulkansara** [comment]
+1 wiating for this in UI.grid 3.0

**Comment by juristr** [comment]
Does anyone already have a working example of a spanning header column using the latest 3.0 RC??
Thx!

**Comment by booybooy** [comment]
+1 for getting this on ui.grid

**Comment by cpapernik** [comment]
Thanks for all the great work so far on ui.grid.  This feature would be very useful and greatly improve the UX for many use cases.

**Comment by pascaloliv** [comment]
+1 ! This feature would be very very useful :+1:

**Comment by coffeetime96** [comment]
+1, this feature would be very helpful!

**Comment by Cadrach** [comment]
I have built a plugin following the same layout as the others from the lib. It works for creating one header line, not many as in the first post. Simply define a "group" property in you column definition. It will be used as the title, and all column with the same name will be under the same group. I think you have to order them by group though.

Works with pinning & resize.

```javascript
(function () {
    'use strict';

    var module = angular.module('ui.grid.actived.group', ['ui.grid']);

    module.service('uiGridActivedGroupService', ['$q', '$templateCache', '$timeout', 'uiGridConstants', 'gridUtil',
        function ($q, $templateCache, $timeout, uiGridConstants, gridUtil) {

            //Add our header row, just once
            var tplName = 'ui-grid/ui-grid-header';
            var tpl = angular.element($templateCache.get(tplName));
            tpl.find('.ui-grid-header-viewport').prepend('<div class="ui-grid-header-group"><div style="width:{{group.width}}px" ng-repeat="group in grid.groups" ng-show="group.width>0">{{group.name}}</div>')
            $templateCache.put(tplName, tpl.html());

            var service = function(grid){

                grid.groups = [];

                var computeWidth = function(){
                    //Use $timeout to process during next $digest, to allow pinning to have taken effect
                    $timeout(function(){
                        if(grid.groups[0].$$hashKey){
                            //console.log('COMPUTE WIDTH', _.pluck(grid.groups,'$$hashKey'));
                            grid.groups.forEach(function(group){
                                var width = 0;
                                group.columns.forEach(function(col){
                                    var pinned = col.renderContainer == 'left' || col.renderContainer == 'right';
                                    width+= col.visible && !pinned ? col.width:0;
                                });
                                group.width = width;
                            })
                        }
                    })
                };

                var initGroups = function(){
                    if( ! grid.groups.length){
                        console.log('INIT GROUPS');
                        grid.columns.forEach(function(col){
                            var group = _.findWhere(grid.groups, {name: col.colDef.group});
                            if( ! group){
                                group = {
                                    name: col.colDef.group,
                                    columns: []
                                };
                                grid.groups.push(group);
                            }
                            group.columns.push(col);
                        })
                    }
                }

                //Register processor to compute again width when needed
                var debounceCompute = gridUtil.debounce(computeWidth, 50);
                grid.registerColumnsProcessor(function(renderableColumns){
                    debounceCompute();
                    return renderableColumns;
                });

                //Register column builder
                grid.buildColumns().then(function(data){
                    initGroups();
                    return data;
                })
            };

            return service;

        }]);

    module.directive('uiGridActivedGroup', ['gridUtil', 'uiGridActivedGroupService', function (gridUtil, uiGridActivedGroupService) {
        return {
            replace: true,
            priority: 999,
            require: '^uiGrid',
            scope: true,
            compile: function () {
                return {
                    pre: function ($scope, $elm, $attrs, uiGridCtrl) {
                        uiGridActivedGroupService(uiGridCtrl.grid);
                    },
                    post: function ($scope, $elm, $attrs, uiGridCtrl) {
                    }
                };
            }
        };
    }]);

})();
```

```css
.ui-grid-header-group{
    width: 10000px;
    height: 26px;
    &>div{
        display: inline-block;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;

        border: 1px solid rgb(212, 212, 212);
        border-top: 0;
        border-left: 0;

        background-image: -webkit-gradient(linear, 0% 100%, 0% 0%, from(rgb(238, 238, 238)), to(rgb(255, 255, 255)));
        padding: 3px;
        -webkit-transition: all 0.2s ease-in-out;
        -moz-transition: all 0.2s ease-in-out;
        -o-transition: all 0.2s ease-in-out;
        transition: all 0.2s ease-in-out;
    }
}
.ui-grid-pinned-container .ui-grid-header-group{
    //Hide header of pinned container
    display: none;
}
```
