### ISSUE TITLE
Misalignment Column header separators with actual column separators in high resolution display

### ISSUE THREAD

**Issue by banajit** [angular-ui/ui-grid#6799]
It has been noticed that, in high resolution display, column headers separator are not aligned with actual data column separator. The issue exist in the ui-grid example itself. 

http://ui-grid.info/docs/#!/tutorial/321_singleFilter

Also screenshot attached.
**Tested monitor resolution:  1920x1080**

Please let me know if there is any workaround exist.
![misalign headers](https://user-images.githubusercontent.com/7721153/42505748-510862aa-845d-11e8-9ba3-e17d346cfd48.png)

**Comment by m4m4m4** [comment]
This also occurs on windows if the display DPI setting is set on anything but 100% on Windows
It also happens if you zoom in to a odd percentage

The issue is that the header display property is table based and the content is block based.

Here is a simple css fix that changes the header to be flexbox based instead:
```css
/* UI-Grid header non-alignment fix */
.ui-grid-header-cell-wrapper {
    display:flex;
    width:100%;
}
.ui-grid-header-cell-row {
    display: flex; 
    flex-direction: row;
    flex-wrap: wrap;
}
.ui-grid-header-cell {
    display:block;
}
/* Fixes IE word-wrap if needed on header cells */
.ui-grid-header-cell > div {
    flex-basis:100%;
}
```
And here is a plunker with all features enabled with the fix
http://plnkr.co/edit/04D1vmJRROXkKGfxNZfU?p=preview

I changed the less file in the source code and no tests seem to fail. I however know that flexbox has some odd behaviour in IE and Safari. This will also probably break every custom template out there.
Let me know if this is the direction you want to take and i'll submit it as a pull request @mportuga
