### ISSUE TITLE
column span not working after 4.6.2 - with sample plunker

### ISSUE THREAD

**Issue by SnpDeveloper** [angular-ui/ui-grid#6939]
Hello,

I have added a colspan functionality which seems to work fine in all cases until 4.6.2. From 4.6.3 css seems to break column span functionality.

Here is a sample plunker i have added.

http://next.plnkr.co/edit/EtA1KEv1rjporY7f?preview

In plunker if you change

  <link rel="stylesheet" href="http://ui-grid.info/release/4.6.2/ui-grid.css" 

to anything greater than 4.6.2 column headers seems to be hidden.

Any help appreciated.

**Comment by dmitry-borzov** [comment]
The following changes in 4.6.3 breaks column span:
```css
.ui-grid-header-cell-row {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: row;
  flex-direction: row;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
}
```
For comparison, v4.6.2:
```css
.ui-grid-header-cell-row {
  display: table-row;
}
```
